name: Tests

on:
  pull_request:
  push:
    branches: [ 4.x-dev ]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9', '3.10' ]
    name: Tests (Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Pytest
        run: |
          pip install --upgrade pip
          pip install pytest
          python --version ; pip --version ; pytest --version
        shell: bash
      - name: Run Tests
        run: |
          cd tests
          ./run_tests.sh
        shell: bash